prettytailstrabajo/prettytails/urls.py
from django.contrib import admin
from django.urls import path, include
from tasks import views


urlpatterns = [
    path('', include('tasks.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
      
]

prettytailstrabajo/tasks/urls.py
from django.urls import path
from tasks.views import home, exit, register, nosotros,Perfil, NMascotas, infomascotas, agregarMascota, agregar_desparacitacion, agregar_vacunacion, agregar_atencion
from accounts.views import agregarPerfil
from django.conf import settings
from django.conf.urls.static import static,serve

# La lista `urlpatterns` se utiliza para mapear URLs a vistas en el framework web Django. Cada llamada a la función `path`
# representa un patrón de URL y especifica la función de vista correspondiente que debe ser
# cuando se accede a esa URL.

urlpatterns = [
   path('', home, name='home'),
   
   path('logout/', exit, name='exit'),
   path('register/', register, name='register'),
   path('nosotros/', nosotros, name='nosotros'),
   path('NMascotas/', NMascotas, name='NMascotas'),
   path('agregar_vacunacion/<int:mascota_id>/', agregar_vacunacion, name='agregar_vacunacion'),
   path('mascotas/<int:mascota_id>/', infomascotas, name='infomascotas'),
   path('Perfil/', Perfil, name='Perfil'),
   path('agregarPerfil/', agregarPerfil, name='agregarPerfil'),
   path('agregarMascota/', agregarMascota, name='agregarMascota'),
   path('agregar_atencion/<int:mascota_id>/', agregar_atencion, name='agregar_atencion'),
   path('agregar_desparacitacion/<int:mascota_id>/', agregar_desparacitacion, name='agregar_desparacitacion'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prettytailstrabajo/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.conf import settings
from django.urls import reverse

class Profile(models.Model):
    """
    El código anterior define un modelo de Perfil con campos para la información del usuario y crea un perfil para
    cada usuario cuando se crea.
    
    :param remitente: El parámetro "sender" en el código se refiere a la clase de modelo que está enviando la
    señal. En este caso, el emisor es el modelo User
    :param instancia: El parámetro "instance" se refiere a la instancia del modelo de usuario que se está guardando o creando.
    está guardando o creando. En este caso, representa el objeto usuario
    :param creado: El parámetro "created" es un valor booleano que indica si se ha creado una nueva instancia del modelo
    se ha creado una nueva instancia del modelo de usuario o se ha actualizado una instancia existente.
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile', verbose_name='Usuario')
    rut_user = models.IntegerField(null=True, blank=True, verbose_name='Rut')
    address = models.CharField(max_length=50, null=True, blank=True, verbose_name='Dirección')
    location = models.CharField(max_length=50, null=True, blank=True, verbose_name='Comuna')
    telephone = models.CharField(max_length=50, null=True, blank=True, verbose_name='Teléfono')

    class Meta:
        verbose_name = 'perfil'
        verbose_name_plural = 'perfiles'
        ordering = ['-id']

    def __str__(self):
        return self.user.username

def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

post_save.connect(create_user_profile, sender=User)
post_save.connect(save_user_profile, sender=User)

# La clase anterior define un modelo para una mascota, con varios atributos como tipo, nombre, edad, sexo,
# color, fecha de nacimiento, raza, y una clave externa a un perfil de usuario.
class Mascota(models.Model):
    tipo_mascota = models.CharField(max_length=20)
    nombre = models.CharField(max_length=30,null=False,  verbose_name='nombre mascota')
    edad = models.IntegerField(null=False, verbose_name='edad')
    sexo = models.CharField(max_length=20,null=False, verbose_name='sexo')
    color = models.CharField(max_length=30,null=False,  verbose_name='color mascota')
    fecha_nacimiento = models.DateField(null=False,  verbose_name='fecha_nacimiento')
    raza = models.CharField(max_length=30,null=False, verbose_name='raza')
    rut_user = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='rut')

    def __str__(self):
        return self.nombre
    
# La clase Vacunacion representa un registro de vacunacion para una mascota, incluyendo el nombre de la vacuna,
# el tipo de vacuna, y un documento opcional asociado a la vacuna.
class Vacunacion(models.Model):
    mascota = models.ForeignKey(Mascota, on_delete=models.CASCADE)
    nombre_vacuna = models.CharField(max_length=100)
    tipo_vacuna = models.CharField(max_length=100)
    documento = models.FileField(upload_to='infomascotas/',null=True)
    def get_documento_url(self):
        if self.documento:
            return settings.MEDIA_URL + str(self.documento)
        return ''
    
    def __str__(self):
        return self.nombre_vacuna
    
# La clase `Desparacitacion` representa un modelo para registros de desparasitacion de una mascota, con campos
# para la mascota, nombre de la desparasitacion, tipo de desparasitacion, y un archivo de documento.
class Desparacitacion(models.Model):
    mascota = models.ForeignKey(Mascota, on_delete=models.CASCADE)
    nombre_desparacitacion = models.CharField(max_length=100)
    tipo_desparacitacion = models.CharField(max_length=100)
    documento = models.FileField(upload_to='infomascotas/',null=True)
    def get_documento_url(self):
        if self.documento:
            return settings.MEDIA_URL + str(self.documento)
        return ''
    
    def __str__(self):
        return self.nombre_desparacitacion

# La clase `Atencion` representa un modelo para la atención de una mascota, con atributos como la mascota, el
# nombre de la atención, el tipo de atención, y un documento asociado a la atención.
class Atencion(models.Model):
    mascota = models.ForeignKey(Mascota, on_delete=models.CASCADE)
    nombre_atencion = models.CharField(max_length=100)
    tipo_atencion = models.CharField(max_length=100)
    documento = models.FileField(upload_to='infomascotas/',null=True)
    def get_documento_url(self):
        if self.documento:
            return settings.MEDIA_URL + str(self.documento)
        return ''
    
    def __str__(self):
        return self.nombre_atencion

prettytailstrabajo/tasks/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

# La clase CustomUserCreationForm es una subclase de UserCreationForm que especifica los campos para la
# creación de usuarios.
class CustomUserCreationForm(UserCreationForm):
	
	class Meta:
		model = User
		fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']
		

prettytailstrabajo/tasks/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.urls import reverse
from accounts.forms import PerfilForm,MascotaForm1,VacunacionForm,DesparacitacionForm,AtencionForm
from .forms import CustomUserCreationForm
from django.contrib.auth import authenticate, login




def home(request):
    """
    La función `home` devuelve una plantilla HTML renderizada para la página de inicio.
    
    parámetro request: El parámetro request es un objeto que representa la petición HTTP realizada por el
    usuario. Contiene información sobre la petición, como el método utilizado (GET o POST), las cabeceras
    el agente de usuario y los datos enviados con la solicitud. En este caso, el objeto de solicitud se pasa a
    el renderizado
    :return: la plantilla renderizada 'tareas/home.html'.
    """
    return render(request,'tasks/home.html')

@login_required
def Perfil(request):
    """
    La función "Perfil" es una función de vista en Django que gestiona la creación y visualización de perfiles de usuario.
    de usuario.
    
    :param request: El parámetro `request` es un objeto que representa la petición HTTP realizada por el
    usuario. Contiene información sobre la petición, como el usuario que la realiza, el método
    utilizado (GET o POST), y cualquier dato enviado con la petición.
    :return: una plantilla HTML renderizada llamada 'profile/Perfil.html' junto con un diccionario de contexto
    que contiene las variables 'form' y 'user'.
    """
    user = request.user  # Obtener el usuario actualmente autenticado

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        form1 = PerfilForm(request.POST)
        if form.is_valid() and form1.is_valid():
            # Guardar los datos del formulario en la base de datos
            form.save()

            # Redireccionar al detalle del perfil
            return redirect('perfil')
    else:
        form = CustomUserCreationForm(initial={
            'username': user.username,
            'first_name': user.first_name,
            'last_name': user.last_name,
            'email': user.email
        })
        

    return render(request, 'profile/Perfil.html', {'form': form, 'user': user})



def exit(request):
    """
    La función `exit` cierra la sesión del usuario y lo redirige a la página de inicio.
    
    param petición: El parámetro `request` es un objeto que representa la petición HTTP realizada por el
    usuario. Contiene información sobre la petición, como la URL, las cabeceras y cualquier dato enviado con la petición.
    con la solicitud. En este caso, se utiliza para cerrar la sesión del usuario y redirigirlo a la página de inicio
    :return: una redirección a la página 'home'.
    """
    logout(request)
    return redirect('home')

def register(request):
    """
    La función `register` maneja el registro de usuarios validando los datos del formulario, creando un nuevo usuario,
    autenticando al usuario, y redirigiendo a la página de inicio.
    
    param request: El parámetro `request` es un objeto que representa la petición HTTP realizada por el
    usuario. Contiene información sobre la petición, como el método utilizado (GET o POST), la sesión del usuario y cualquier dato enviado con la petición.
    y cualquier dato enviado con la petición
    :return: El código devuelve una plantilla HTML llamada 'registration/register.html' con el diccionario de datos
    diccionario de datos como contexto.
    """
    data = {
        'form': CustomUserCreationForm()
    }

    if request.method == 'POST':
        user_creation_form = CustomUserCreationForm(data=request.POST)

        if user_creation_form.is_valid():
            user_creation_form.save()

            user = authenticate(username=user_creation_form.cleaned_data['username'], password=user_creation_form.cleaned_data['password1'])
            login(request, user)
            
            return redirect('home')
    return render(request,'registration/register.html', data)

def nosotros(request):
    """
    La función "nosotros" renderiza la plantilla "nosotros.html".
    
    param petición: El parámetro `request` es un objeto que representa la petición HTTP realizada por el
    cliente. Contiene información sobre la petición, como el método HTTP utilizado (GET, POST, etc.),
    las cabeceras, el agente de usuario y el cuerpo de la petición. En este caso, el objeto `request` es
    :return: la plantilla renderizada 'tareas/nosotros.html'
    """
    return render(request,'tasks/nosotros.html')







@login_required  
def agregarMascota(request):
    """
    La función "agregarMascota" es una función de vista en Django que añade una nueva mascota a la base de datos,
    asociada al usuario conectado en ese momento.
    
    :param request: El objeto request representa la petición HTTP que el usuario realizó para acceder a la
    vista. Contiene información como la sesión del usuario, el método HTTP utilizado (GET o POST), y
    cualquier dato enviado en la solicitud
    :return: una plantilla HTML renderizada llamada 'mascotas/agregarMascota.html' con una variable de contexto
    que contiene el formulario.
    """
    form = MascotaForm1()
    if request.method == 'POST':
        form = MascotaForm1(request.POST)
        if form.is_valid():
            mascota = form.save(commit=False)
            mascota.rut_user = request.user.profile  # Asignar el rut_user al perfil del usuario actual
            mascota.save()
            return redirect('NMascotas')
    
    context = {'form': form}
    return render(request, 'mascotas/agregarMascota.html', context)





def NMascotas(request):
    # Obtener el usuario actualmente autenticado
    user = request.user

    # Filtrar las mascotas en base al usuario actual
    mascotas_list = Mascota.objects.filter(rut_user_id=user.id)

    context = {
        'mascotas': mascotas_list
    }
    return render(request, 'mascotas/NMascotas.html', context)

from accounts.models import Mascota, Vacunacion,Desparacitacion,Atencion






def infomascotas(request, mascota_id):
    """
    La función `infomascotas` recupera información sobre una mascota concreta, incluyendo sus vacunas
    desparasitaciones y atenciones médicas, y la muestra en una plantilla.
    
    parámetro request: El parámetro request es un objeto que representa la petición HTTP realizada por el
    cliente. Contiene información como el método de solicitud, las cabeceras y el cuerpo.
    :param mascota_id: El parámetro `mascota_id` es el ID de la mascota de la que se desea obtener información.
    recuperar información. Se utiliza para obtener el objeto mascota específico de la base de datos mediante la función
    consulta `Mascota.objects.get(id=mascota_id)`.
    :return: una plantilla HTML renderizada llamada `infomascotas.html` con los datos del contexto.
    """
    mascota = Mascota.objects.get(id=mascota_id)
    vacunaciones = Vacunacion.objects.filter(mascota=mascota)
    desparasitaciones = Desparacitacion.objects.filter(mascota=mascota)
    atenciones = Atencion.objects.filter(mascota=mascota)

    context = {
        'mascota': mascota,
        'vacunaciones': vacunaciones,
        'desparasitaciones': desparasitaciones,
        'atenciones': atenciones,
    }

    return render(request, 'mascotas/infomascotas.html', context)



def agregar_vacunacion(request, mascota_id):
    """
    La función "agregar_vacunacion" agrega un registro de vacunación para una mascota específica.
    
    :param request: El objeto request representa la petición HTTP que ha realizado el usuario para acceder a la
    vista. Contiene información como la sesión del usuario, el método HTTP utilizado (GET, POST, etc.)
    y cualquier dato enviado con la solicitud
    :param mascota_id: El parámetro `mascota_id` es el ID de la mascota para la que queremos
    añadir un registro de vacunación
    :return: una plantilla HTML renderizada llamada `mascotas/agregar_vacunacion.html` con las variables contextuales
    formulario' y 'mascota'.
    """
    mascota = Mascota.objects.get(id=mascota_id)

    if request.method == 'POST':
        form = VacunacionForm(request.POST, request.FILES)
        if form.is_valid():
            vacunacion = form.save(commit=False)
            vacunacion.mascota = mascota  # Asignar la mascota relacionada
            vacunacion.save()
            return redirect('infomascotas', mascota_id=mascota_id)
    else:
        form = VacunacionForm()

    context = {
        'form': form,
        'mascota': mascota
    }
    return render(request, 'mascotas/agregar_vacunacion.html',context)

def agregar_atencion(request, mascota_id):
    """
    La función "agregar_atencion" añade un nuevo objeto "Atencion" a un objeto "Mascota" específico y
    redirige a la página de "infomascotas".
    
    :param petición: El objeto request representa la petición HTTP realizada por el usuario. Contiene
    información como la sesión del usuario, el método HTTP utilizado (GET, POST, etc.), y cualquier dato
    enviados con la solicitud
    param mascota_id: El parámetro `mascota_id` es el ID de la mascota para la que se está añadiendo la atencion
    (cuidado). Se utiliza para recuperar el objeto mascota específico de la base de datos.
    :devuelve: una plantilla HTML renderizada llamada `mascotas/agregar_atencion.html` con las variables de contexto
    'formulario' y 'mascota'.
    """
    mascota = Mascota.objects.get(id=mascota_id)

    if request.method == 'POST':
        form = AtencionForm(request.POST, request.FILES)
        if form.is_valid():
            atencion = form.save(commit=False)
            atencion.mascota = mascota  # Asignar la mascota relacionada
            atencion.save()
            return redirect('infomascotas', mascota_id=mascota_id)
    else:
        form = AtencionForm()

    context = {
        'form': form,

prettytailstrabajo/tasks/templates/profile/Perfil.html
{% extends 'tasks/base.html' %}

{% block content %}
<br>
<h3 style="color: aliceblue;">Perfil</h3>
<br>
<div class="row">
  <div class="col-md-12">
    <div class="card mx-auto bg-dark" style="width: 40rem; border-radius: 1rem; border-color: #ffffff;">
      <div class="card-body">
        <h1 style="color: aliceblue;">Datos del usuario</h1>
        <table class="table">
          <thead>
            <tr>
              <th>Nombre de usuario</th>
              <th>Nombre</th>
              <th>Apellidos</th>
              <th>Correo electrónico</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>{{ form.username.value }}</td>
              <td>{{ form.first_name.value }}</td>
              <td>{{ form.last_name.value }}</td>
              <td>{{ form.email.value }}</td>      
            </tr>
          </tbody>
        </table>
        {% if user.profile %}
        <h1 style="color: aliceblue; ">Datos del Perfil</h1>
       
          <table class="table " style="background-color: #bcbefa;">
            <thead >
              <tr>
                <th>Rut</th>
                <th>Dirección</th>
                <th>Comuna</th>
                <th>Teléfono</th>
                
              </tr>
            </thead>
            <tbody>
              {% for profile in profile %}
              <tr>
                <td>{{ user.profile.rut_user }}</td>
                <td>{{ user.profile.address }}</td>
                <td>{{ user.profile.location }}</td>
                <td>{{ user.profile.telephone }}</td>   
                
                
              </tr>
              {% endfor %}
              <tr>
                <td>{{ user.profile.rut_user }}</td>
                <td>{{ user.profile.address }}</td>
                <td>{{ user.profile.location }}</td>
                <td>{{ user.profile.telephone }}</td>   
                </tr>
            </tbody>
          </table>
        {% else %}
          <strong>No se encuentran Datos</strong>
        {% endif %}
        <br>
        <a href={% url 'agregarPerfil' %} class="btn btn-primary" style="float: right;">Actualizar del Perfil</a>
      </div>
    </div>
  </div>
</div>
<br>
<br>
<br>
{% endblock %}

prettytailstrabajo/tasks/templates/profile/agregarPerfil.html
{% extends 'tasks/base.html' %}

{% block content %}
<html>
<head>
    <title>Rellene campos del perfil</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.5.0/css/bootstrap.min.css">
</head>
<body>
    <div class="card card-sm" style="background-color: #bcbefa; margin-top: 2rem;">
        <h1 class="card-header">Rellene campos del perfil</h1>
        <div class="card-body">
            <form method="POST" action="">
                {% csrf_token %}
                <p>
                    <label for="id_rut_user" style="color: black;">rut:</label>
                    <input type="number" name="rut_user" id="id_rut_user" class="form-control" placeholder="123456789">
                </p>
                <p>
                    <label for="id_address" style="color: black;">Dirección:</label>
                    <input type="text" name="address" maxlength="50" id="id_address" class="form-control">
                </p>
                <p>
                  <label for="id_location" style="color: black;">Comuna:</label>
                  <select name="location" id="id_location" class="form-select">
                      <option value=""></option>
                      <option value="La Reina">La Reina</option>
                      <option value="Las Condes">Las Condes</option>
                      <option value="Vitacura">Vitacura</option>
                      <option value="Peñalolen">Peñalolén</option>
                      <option value="Macul">Macul</option>
                      <option value="La Florida">La Florida</option>
                  </select>
                </p>
                <p>
                    <label for="id_telephone" style="color: black;">Teléfono:</label>
                    <input type="text" name="telephone" maxlength="50" id="id_telephone" class="form-control">
                </p>
                <button type="submit" class="btn btn-primary">Guardar</button>
            </form>
        </div>
    </div>
</body>
</html>
{% endblock %}